### ISSUE TITLE
got an error

### ISSUE THREAD

**Issue by fgibnob** [PoorBillionaire/sitereview#12]
$python sitereview.py http://brins.biz/
Traceback (most recent call last):
  File "sitereview.py", line 60, in <module>
    main(args.url)
  File "sitereview.py", line 42, in main
    response = s.sitereview(url)
  File "sitereview.py", line 28, in sitereview
    return json.loads(self.req.content.decode("UTF-8"))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by PoorBillionaire** [comment]
Thanks for the report. It looks like the Sitereview service now returns XML by default, not JSON - which breaks the script (see below). I'll sit down and take a look at it this weekend.

```
<CategorizationResult>
    <url>http://brins.biz/</url>
    <unrated>false</unrated>
    <curTrackingId>1757937</curTrackingId>
    <locked>false</locked>
    <lockedMessage/>
    <lockedSpecialNote/>
    <multiple>false</multiple>
    <multipleMessage/>
    <rateDate>Last Time Rated/Reviewed: > {{days}} days {{legacy}}The URL submitted for review was rated more than {{days}} days ago.  The default setting for Symantec SG clients to download rating changes is once a day.  There is no need to show ratings older than this. Since Symantec's desktop client K9 and certain OEM partners update differently, ratings may differ from those of a Symantec SG as well as those present on the Site Review Tool.</rateDate>
    <categorization>
        <categorization>
            <num>43</num>
            <name>Malicious Sources/Malnets</name>
        </categorization>
    </categorization>
    <threatriskLevel></threatriskLevel>
    <threatriskLevelEn></threatriskLevelEn>
    <linkable>false</linkable>
    <securityCategory>true</securityCategory>
    <securityCategoryIds>
        <securityCategoryIds>43</securityCategoryIds>
        <securityCategoryIds>102</securityCategoryIds>
        <securityCategoryIds>44</securityCategoryIds>
        <securityCategoryIds>92</securityCategoryIds>
        <securityCategoryIds>18</securityCategoryIds>
    </securityCategoryIds>
    <suggestion/>
    <resolvedDetail>
        <resolveEnabled>true</resolveEnabled>
        <ipAddress/>
    </resolvedDetail>
    <followedUrl/>
    <translatedCategories>
        <de>
            <num>43</num>
            <name>Bösartige Quellen/Malnets (Malicious Sources/Malnets)</name>
        </de>
        <zh_TW>
            <num>43</num>
            <name>惡意來源/惡意網路 (Malicious Sources/Malnets)</name>
        </zh_TW>
        <ja>
            <num>43</num>
            <name>悪意のある発信元/マルネット (Malicious Sources/Malnets)</name>
        </ja>
        <en>
            <num>43</num>
            <name>Malicious Sources/Malnets</name>
        </en>
        <fr>
            <num>43</num>
            <name>Sources malveillantes/malnets (Malicious Sources/Malnets)</name>
        </fr>
        <es>
            <num>43</num>
            <name>Fuentes de software malicioso/malnets (Malicious Sources/Malnets)</name>
        </es>
        <zh>
            <num>43</num>
            <name>恶意来源/恶意网络 (Malicious Sources/Malnets)</name>
        </zh>
    </translatedCategories>
    <ratingDts>OLDER</ratingDts>
    <ratingDtsCutoff>7</ratingDtsCutoff>
</CategorizationResult>
```

**Comment by fgibnob** [comment]
thanks!!!!

**Comment by aarora79** [comment]
I also stumbled upon the same issue. FWIW this is what i did to fix it. I did not need the date field, and my URL was simply the domain name itself.

```
class SiteReview(object):
    def __init__(self):
        self.baseurl = "https://sitereview.bluecoat.com/resource/lookup"
        self.headers = {"User-Agent": "Mozilla/5.0", "Content-Type": "application/json"}

    def sitereview(self, url):
        self.url = url
        payload = {"url": url, "captcha":""}

        try:
            # print(self.baseurl)
            self.req = requests.post(
                self.baseurl,
                headers=self.headers,
                data=json.dumps(payload),
            )
        except requests.ConnectionError:
            sys.exit("[-] ConnectionError: " \
                     "A connection error occurred")
        return BeautifulSoup(self.req.content.decode("UTF-8"), "lxml")

    def check_response(self, response):
        if self.req.status_code != 200:
            sys.exit("[-] HTTP {} returned".format(req.status_code))
        else:
            idx = 1 if len(response.categorization.contents) > 1 else 0
            category = response.categorization.contents[idx]
            for child in category.children:
                if child.name == "name":
                    self.category = child.string
            self.date = None
```

**Comment by fgibnob** [comment]
thanks aarora79 it works! 👍  could be nice if you could submit and recategorized :)

**Comment by PoorBillionaire** [comment]
Apologies for the delay. I pushed a fix which resolves this issue - I'll keep this open for a couple of days if someone would like to confirm.

**Comment by PoorBillionaire** [comment]
Closing this out as resolved - thanks again
