### ISSUE TITLE
API seems to be down

### ISSUE THREAD

**Issue by jordanbuchman** [PoorBillionaire/sitereview#7]
When running the script, I get this error:
```
Traceback (most recent call last):
  File "sitereview.py", line 65, in <module>
    main(args.url)
  File "sitereview.py", line 47, in main
    response = s.sitereview(url)
  File "sitereview.py", line 28, in sitereview
    return json.loads(self.req.content.decode("UTF-8"))
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

After altering the script to print the raw response, it looks like something is wrong with the endpoint:
```
<html><head><title>Apache Tomcat/7.0.52 (Ubuntu) - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 403 - Security violation.</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Security violation.</u></p><p><b>description</b> <u>Access to the specified resource has been forbidden.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.52 (Ubuntu)</h3></body></html>
```

Am I using the script wrong, or is this an error with Site Review?

**Comment by grayfold3d** [comment]
I get the same thing. Tried accessing API using PowerShell and received the following error so it looks like an issue with the API.
```
Apache Tomcat/7.0.52 (Ubuntu) - Error report HTTP Status 403 - Security violation.type Status reportmessage Security violation.description Access to the specified 
resource has been forbidden.Apache Tomcat/7.0.52 (Ubuntu)
```

**Comment by PoorBillionaire** [comment]
Thanks, I'm aware. It appears that the site changed. I'll take a look at some point soon, just haven't had time yet.

**Comment by PoorBillionaire** [comment]
Looks like the API was redesigned, in a good way. Among other things SSL was implemented, the API endpoint changed, and the request/response data is now JSON.

I updated the script to restore functionality and things look good so far. @jordanbuchman @yemyslf let me know if you're seeing successful requests again.

Thanks all

--
Adam

**Comment by PoorBillionaire** [comment]
Commit ac4db5dfe8df37f461afba63c37413e0835a511b should resolve this one

**Comment by grayfold3d** [comment]
Looks good. Thanks for fixing!
